name: wohland_wind_2021
channels:
    - conda-forge
dependencies:
    - python=3.8
    - matplotlib
    - numpy
    - xesmf
    - scipy
    - cartopy
    - xarray
    - shapely
    - pandas
    - rasterio
    - openpyxl
    - cdo
    - netcdf4
    - nc-time-axis>=1.2.0